#!/bin/bash

echo "STARTSTART start new chain5 " >> log5
for i in uni pre
do
  echo "STARTSTART  chain5 $i at $(date)" >> log5
  stdbuf -oL prism -cuddmaxmem 1500000 -fixdl chain5$i.pm -const k=20,N=10:20 chain5.props -exportresults chain5$i.res >> log5
  echo "ENDEND  chain5 $i at $(date)" >> log5
done
